#!/bin/bash

echo "Iniciando configuração da CLI de Scan da N-MultiFibra";

cp ./src/nm /bin/;
cp ./nm.config /etc/;

chmod +x /bin/nm;

apt update;
apt install tcpdump scp;

echo "Instalação concluida";
